# Generated by Django 3.1.7 on 2021-04-05 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_in_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
