# Generated by Django 3.1.7 on 2021-04-06 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tag',
            new_name='tags',
        ),
    ]
