# Generated by Django 3.1.7 on 2021-04-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(default='Информация о пользователе', max_length=100),
            preserve_default=False,
        ),
    ]
