# Generated by Django 3.2 on 2021-04-15 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_profile_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
