# Generated by Django 3.2 on 2021-04-17 07:54

from django.db import migrations
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210415_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=thumbnails.fields.ImageField(null=True, upload_to='main/static/images/goods'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=thumbnails.fields.ImageField(null=True, upload_to='main/static/images/users'),
        ),
    ]
