# Generated by Django 3.2 on 2021-04-17 08:23

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210417_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='main/static/images/goods'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='main/static/images/users'),
        ),
    ]
