# Generated by Django 3.2 on 2021-04-23 08:36

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210417_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='mediaimages/goods'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='media/images/users'),
        ),
    ]
